### PR TITLE
Update action URL and add version tag

### PR DESCRIPTION
**Pull request by sloede**
Once this is merged, I would like to tag the merge commit with `v1.0.0` and `v1`

### CODE REVIEW

**Comment by sloede** [comment]
Alternatively, we could also just use `@main` and keep living on the edge (might be less hassle, too)

**Review by ranocha — COMMENTED** [review]
Can the line

https://github.com/trixi-framework/add-pr-review-checklist/blob/184ea3bfb6cdc90be3fac019e1291684f81e1d04/action.yml#L28

be used to insert malicious code since it includes something set purely by the creator of a PR (the description of the PR)?

**Comment by ranocha** [comment]
> Alternatively, we could also just use `@main` and keep living on the edge (might be less hassle, too)

I prefer `v1`

**Comment by sloede** [comment]
> Can the line
> 
> https://github.com/trixi-framework/add-pr-review-checklist/blob/184ea3bfb6cdc90be3fac019e1291684f81e1d04/action.yml#L28
> 
> be used to insert malicious code since it includes something set purely by the creator of a PR (the description of the PR)?

I don't see how, unless the Node.js string library itself is compromised. It would be different if the input interpolation could be modified by the user, but since it comes directly from the workflow file, IMHO it should be safe.

**Review by ranocha — APPROVED** [review]

**Pull request merged**
